dot -Tpng Doublet_calling.dot > Doublet_calling.png
dot -Tpng LinearChain_htmapdegs.dot > LinearChain_htmapdegs.png
dot -Tpng SingleR_singleref.dot > SingleR_singleref.png
dot -Tpng add_doubletinfo.dot > add_doubletinfo.png
dot -Tpng clustering_n_pca_simple.dot > clustering_n_pca_simple.png
dot -Tpng end_to_end_multisample.dot > end_to_end_multisample.png
dot -Tpng end_to_end_seurat_singlesample.dot > end_to_end_seurat_singlesample.png
dot -Tpng htmap_degs.dot > htmap_degs.png
dot -Tpng linear_chain_adddoublets_seurat.dot > linear_chain_adddoublets_seurat.png
dot -Tpng make_gene_featplots.dot > make_gene_featplots.png
dot -Tpng merge_doublets_multisample.dot > merge_doublets_multisample.png
dot -Tpng multisample_seurat.dot > multisample_seurat.png
dot -Tpng multisample_seurat_doublet_singler.dot > multisample_seurat_doublet_singler.png
dot -Tpng plot_qc.dot > plot_qc.png
dot -Tpng recluster_renorm_rerun_singleR.dot > recluster_renorm_rerun_singleR.png
dot -Tpng rpca_integration.dot > rpca_integration.png
dot -Tpng scatter_Doubletcall.dot > scatter_Doubletcall.png
dot -Tpng scatter_deg.dot > scatter_deg.png
dot -Tpng scatter_gather_Doubletcall.dot > scatter_gather_Doubletcall.png
dot -Tpng scatter_gather_Doubletcall_multisample.dot > scatter_gather_Doubletcall_multisample.png
dot -Tpng scatter_gather_doublet_singlesample.dot > scatter_gather_doublet_singlesample.png
dot -Tpng scatter_gather_scsorter.dot > scatter_gather_scsorter.png
dot -Tpng scatter_gather_singleR.dot > scatter_gather_singleR.png
dot -Tpng scatter_rpca.dot > scatter_rpca.png
dot -Tpng scatter_singleR.dot > scatter_singleR.png
dot -Tpng scsorter_run.dot > scsorter_run.png
dot -Tpng seurat_counts_to_anndata.dot > seurat_counts_to_anndata.png
dot -Tpng singleR_immune_nonimmune_pipeline.dot > singleR_immune_nonimmune_pipeline.png
dot -Tpng single_sample_filtering_n_clustering.dot > single_sample_filtering_n_clustering.png
dot -Tpng single_sample_filtering_nd_doublets.dot > single_sample_filtering_nd_doublets.png
dot -Tpng single_sample_seurat.dot > single_sample_seurat.png
dot -Tpng subset_renormalize_recluster.dot > subset_renormalize_recluster.png
